project_id = "ndghbgkcpjfevkygfxds"

[functions.classify-business]
verify_jwt = false

[functions.sync-experts]
verify_jwt = false

[functions.telegram-auth]
verify_jwt = false

[functions.sync-clients]
verify_jwt = false

[functions.ai-search-clients]
verify_jwt = false

[functions.send-telegram-message]
verify_jwt = false

[functions.sync-telegram-profile]
verify_jwt = false

[functions.notify-expert-selection]
verify_jwt = false

[functions.sync-cities]
verify_jwt = false
